linters-settings:
  govet:
    enable-all: true
  gocyclo:
    min-complexity: 10
  dupl:
    threshold: 100
  lll:
    line-length: 140
  nlreturn:
    block-size: 4
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  gocritic:
      enable-all: true
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
  tagalign:
    strict: true
    order:
      - name
      - short
      - env
      - default
      - help
linters:
  enable:
    - bodyclose
    - errcheck
    - funlen
    - gochecknoglobals 
    - gochecknoinits 
    - gocognit 
    - goconst
    - gocyclo
    - godot
    - gofmt
    - goimports
    - gosec 
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nlreturn
    - noctx
    - paralleltest
    - prealloc
    - revive
    - sloglint
    - staticcheck
    - stylecheck
    - tagalign
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - unused
    - usestdlibvars
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go$
      linters:
        - nlreturn
        - govet
        - funlen
        - gocyclo
  exclude-dirs:
    - testdata