name: Generate code coverage badge

# on:
#   pull_request:
#     branches:
#       - main

on: [push]


jobs:
  test:
    runs-on: ubuntu-latest
    name: Update coverage badge
    steps:
      - name: Test
        run: go test -v ./...

      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          report: true
          chart: true
          amend: true
        if: |
          matrix.os == 'ubuntu-latest' &&
          github.event_name == 'push'
        continue-on-error: true
